#!/bin/bash
#
# Run qemu-system-i386 on the baseline OS
#

#
# other options:
#	-nographic
#	-display gtk
#

QEMU=/home/course/csci352/bin/qemu-system-i386

exec $QEMU \
	-serial mon:stdio \
	-drive file=disk.img,index=0,media=disk,format=raw
